name: lint_and_tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e './laser_encoders'
        python -m pip install './laser_encoders[dev]'
        
    - name: isort
      run: cd laser_encoders && isort --check --diff .
      
    - name: black
      run: cd laser_encoders && black --check --diff .

    - name: pytest
      run: pytest laser_encoders
